from .database import Base
from app.achievements.models import *
from app.categories.models import *
from app.courses.models import *
from app.email.models import *
from app.file.models import *
from app.homework.models import *
from app.lessons.models import *
from app.tags.models import *
from app.users.models import *
from app.content.models import *
